name: Build QMK

on:
  push:
    branches: build
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test pwd
      run: util/docker_build.sh lily58/rp2040zero:default
    - name: Release firmware
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: Latest build of lily58/rp2040zero
        draft: false
        prerelease: false
