name: Build QMK

on:
  push:
    branches: [master, build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Library
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build QMK firmware using docker
      run: util/docker_build.sh lily58/rp2040zero:default
    - name: Archive Firmware
      uses: actions/upload-artifact@v3
      with:
        name: lily58-rp2040zero
        path: "*.uf2"

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download firmware
      uses: actions/download-artifact@v2
      with:
        path: release
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%dT%H-%M')" >> "$GITHUB_OUTPUT"
    - name: Release firmware
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: "release/${{ steps.date.outputs.date}}GMT"
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} $tag" \
          release/lily58-rp2040zero*.uf2
