name: Build QMK

on:
  push:
    branches: build
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test pwd
      run: util/docker_build.sh lily58/rp2040zero:default
