name: Build QMK

on:
  push:
    branches: build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build QMK firmware using docker
      run: util/docker_build.sh lily58/rp2040zero:default
    - name: Get current date
      id: date
      run: echo "name=date::$(date +'%Y-%m-%dT%H:%M')" >> "$GITHUB_OUTPUT"
    - name: Release firmware
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ steps.date.outputs.date }}" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${{ steps.date.outputs.date }}" \
          *.uf2 