name: Build QMK

on:
  push:
    branches: build
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build QMK firmware using docker
      run: util/docker_build.sh lily58/rp2040zero:default
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Release firmware
      env:
        GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.date.outputs.date }}
      run: |
        gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes \
          *.uf2       
